apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      name: flask-pod
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: opusidea/exo3:v2

---

apiVersion: v1
kind: Service
metadata:
  name: flask-srv
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 3200
      targetPort: 5000
      nodePort: 30009
  